#pragma once
#include <cstdint>

namespace SDK
{
	enum E_OBJECT_TAG : uint16_t
	{
		ID_TAG_INVALID = 0,
		ID_TAG_CAMERA = 5,
		ID_TAG_PLAYER = 6,
		ID_TAG_PLAYER_SLEEPING = 16,
		ID_TAG_CORPSE = 20009,
		ID_TAG_SKY = 20011,
	};

	enum eBones
	{
		l_hip = 1,
		l_knee,
		l_foot,
		l_toe,
		l_ankle_scale,
		pelvis,
		penis,
		GenitalCensor,
		GenitalCensor_LOD0,
		Inner_LOD0,
		GenitalCensor_LOD1,
		GenitalCensor_LOD2,
		r_hip,
		r_knee,
		r_foot,
		r_toe,
		r_ankle_scale,
		spine1,
		spine1_scale,
		spine2,
		spine3,
		spine4,
		l_clavicle,
		l_upperarm,
		l_forearm,
		l_hand,
		l_index1,
		l_index2,
		l_index3,
		l_little1,
		l_little2,
		l_little3,
		l_middle1,
		l_middle2,
		l_middle3,
		l_prop,
		l_ring1,
		l_ring2,
		l_ring3,
		l_thumb1,
		l_thumb2,
		l_thumb3,
		IKtarget_righthand_min,
		IKtarget_righthand_max,
		l_ulna,
		neck,
		head,
		jaw,
		eyeTranform,
		l_eye,
		l_Eyelid,
		r_eye,
		r_Eyelid,
		r_clavicle,
		r_upperarm,
		r_forearm,
		r_hand,
		r_index1,
		r_index2,
		r_index3,
		r_little1,
		r_little2,
		r_little3,
		r_middle1,
		r_middle2,
		r_middle3,
		r_prop,
		r_ring1,
		r_ring2,
		r_ring3,
		r_thumb1,
		r_thumb2,
		r_thumb3,
		IKtarget_lefthand_min,
		IKtarget_lefthand_max,
		r_ulna,
		l_breast,
		r_breast,
		BoobCensor,
		BreastCensor_LOD0,
		BreastCensor_LOD1,
		BreastCensor_LOD2,
		collision,
		displacement,
	};

	namespace enums
	{
		enum entity_type : uint32_t
		{
			SAMSite, TreeMarker,
			BasePlayer,
			EggHuntEvent,
			RustigeEgg,
			CollectableEasterEgg,
			SleepingBag,
			DecayEntity,
			BaseNPC,
			TunnelDweller,
			StorageContainer,
			SupplyDrop,
			VendingMachineMapMarker,
			ExcavatorArm,
			LightListener,
			ModularCar,
			BasicCar,
			BaseVehicleSeat,
			Horse1,
			BaseRidableAnimal,
			Boar,
			Bear,		
			Deer, LootableCorpse,
			BradleyAPC, BasePortal,
			Chicken,
			Wolf, BuildingPrivlidge,
			Horse, VehicleModuleStorage,
			HotAirBalloon, Helicopter,
			MiniCopter, BaseHelicopterVehicle,
			DroppedItemContainer,
			Container,
			TrainCar,
			ModularCarGarage,
			SubmarineDuo,
			VehicleModuleSeating,
			OreResourceEntity,
			ResourceEntity,
			StashContainer,
			DroppedItem,
			CollectibleEntity,
			BaseMelee,
			patrolhelicopter,
			patrol,
			TreeEntity,
			OreHotSpot, 
			LootContainer,
			FreeableLootContainer,
			Recycler,
			JunkPileWater,
			Keycard,
			HackableLockedCrate,
			ItemPickup,
			Undefined,  
			FlameTurret,
			Trap,
			ZiplineLaunchPoint,
			AutoTurret,
			BearTrap,
			GunTrap,
			Landmine, 
			BaseOven,
			BaseProjectile,
			EnvSync,
			CommunityEntity,
			BuildingBlock,
			RepairBench,
			TreeManager,
			Planner,
			CodeLock,
			HotSpot,
			ProjectileWeaponMod,
			ScientistNPC,
			BaseChair,
			HTNPlayer,
			GrenadeWeapon,
			TorchWeapon,			
			Scientist,

		};
	}
}
